#!/usr/bin/env python3
import os
import sys
import json
import glob
from datetime import datetime

# Add root scripts to path for Gold Logger
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../scripts')))
from gold_logger import log_action

VAULT_ROOT = "AI_Employee_Vault"
LOGS_DIR = os.path.join(VAULT_ROOT, "Logs")
DONE_DIR = os.path.join(VAULT_ROOT, "Done")
NEEDS_ACTION_DIR = os.path.join(VAULT_ROOT, "Needs_Action")

class ExecutiveReporter:
    def generate_weekly_briefing(self):
        log_action("Gold", "ExecutiveReporter", "Briefing Start", "PROCESSING")
        
        today = datetime.now().strftime("%Y-%m-%d")
        report_file = os.path.join(DONE_DIR, f"CEO_Briefing_{today}.md")
        
        try:
            # 1. Gather Metrics
            completed_tasks = len(glob.glob(os.path.join(DONE_DIR, "completed_*.md")))
            pending_tasks = len(glob.glob(os.path.join(NEEDS_ACTION_DIR, "*.md")))
            
            # 2. Analyze Logs (Last 7 days logic simulated by reading all JSONs in Logs)
            total_actions = 0
            errors = 0
            recent_logs = []
            
            for log_file in glob.glob(os.path.join(LOGS_DIR, "*.json")):
                with open(log_file, "r", encoding="utf-8") as f:
                    try:
                        entries = json.load(f)
                        total_actions += len(entries)
                        for entry in entries:
                            if entry.get("status") in ["ERROR", "FAILED", "CRITICAL"]:
                                errors += 1
                            recent_logs.append(entry)
                    except:
                        pass
            
            # 3. Generate Markdown
            content = f"""# 👔 Weekly CEO Executive Briefing
**Date:** {today}
**Generated By:** Ralph Wiggum Autonomous Agent (Gold Tier)

## 📊 Operational Snapshot
- **Active Tasks:** {pending_tasks}
- **Completed Tasks (Total):** {completed_tasks}
- **System Actions Logged:** {total_actions}
- **Error Rate:** {errors} incidents ({(errors/total_actions*100) if total_actions else 0:.1f}%)

## 🚀 High-Level Updates
- **Odoo Integration:** Online (JSON-RPC)
- **Social Media:** Facebook, Instagram, X modules active.
- **Security:** Gold Tier Audit Logging enabled.

## ⚠️ Risk & Audit Summary
"""
            if errors > 0:
                content += "### Recent Incidents:
"
                # Sort logs by timestamp desc and take top 5 errors
                recent_logs.sort(key=lambda x: x.get("timestamp", ""), reverse=True)
                for log in recent_logs:
                    if log.get("status") in ["ERROR", "FAILED", "CRITICAL"]:
                        content += f"- **[{log.get('timestamp')}]** {log.get('skill')}: {log.get('action')} - {log.get('status')}
"
            else:
                content += "No critical incidents reported this week.
"

            content += "
## 🔮 Forward Looking Strategy
"
            content += "Recommend increasing social media post frequency and auditing Odoo customer data sync.
"
            
            # Write Report
            with open(report_file, "w", encoding="utf-8") as f:
                f.write(content)
                
            log_action("Gold", "ExecutiveReporter", "Briefing Complete", "SUCCESS", {"file": report_file})
            return report_file
            
        except Exception as e:
            log_action("Gold", "ExecutiveReporter", "Briefing Failed", "CRITICAL", {"error": str(e)})
            return None

if __name__ == "__main__":
    reporter = ExecutiveReporter()
    print(f"Report generated: {reporter.generate_weekly_briefing()}")
